# Generated by Django 5.2.4 on 2025-07-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_post_author_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('about', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
